apply plugin: 'com.android.library'
//apply from:  "../library.gradle"

android {
    compileSdkVersion 34
    buildToolsVersion "34.0.0"
    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 34
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures{
        buildConfig = true
    }
    namespace 'per.goweii.anylayer'
}

dependencies {
    compileOnly "org.jetbrains.kotlin:kotlin-stdlib:1.9.20"
    compileOnly 'androidx.core:core-ktx:1.7.0'
    api 'androidx.appcompat:appcompat:1.3.1'
}
